

la def fert_type	1	"Compound", modify	/*	DI-AMMONION PHOSPHATE (DAP), 
	CALCIUM AMMONIUM NITRATE (CAN), NITROGEN PHOSPHATE POTASSIUM (NPK),
	23:21:0+4S/CHITOWE, D COMPOUND, SUPER D COMPOUND	*/ 

la def fert_type	2	"Nitrogen", modify	//	UREA, SULFATE OF AMMONIUM (SA)
la def fert_type	3	"Phosphate", modify	//	TRIPLE SUPER PHOSPHATE (TSP), MINJINGU ROCK PHOSPHATE (MRP)



